# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a2389f5eeb8c95d753e811f25c267ee472d0167a4942cd586806e3e797448ec5a57c91b470dffdddb3433e7317667c49b6444ef915d7c264e7c4f1fc889f40c

test:
  secret_key_base: 01b6413a90aa126feeab90b8946c187e886d3062762758684b32e63c322e6bc2c7590fdfabd40ac19d7af9a72de877fa66fba70b450dc9fe8762411d51f1480a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
